name: Deploy prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      github_environment: prod
      deploy_env: prod
