name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      github_environment: dev
      deploy_env: dev
